// Generated by env-type-generator
import { z } from 'zod';

export const envSchema = z.object({
  API_URL: z.string().url(),
  TIMEOUT: z.string().regex(/^[0-9]+s?$/).transform((v) => Number(v.replace('s', ''))*1000).optional().default('10s'),
  FEATURE: z.enum(['on', 'off']),
});

export type Env = z.infer<typeof envSchema>;

export function loadEnv(raw: Record<string, string | undefined>): Env {
  return envSchema.parse(raw);
}