// Code generated by env-type-generator; DO NOT EDIT.
package env

type Config struct {
  ApiUrl string `env:"API_URL" required:true`
  Timeout string `env:"TIMEOUT" required:false`
  Feature string `env:"FEATURE" required:true`
}

// Validate performs basic checks on required variables.
func (c *Config) Validate() []string {
  var errs []string
  if c.ApiUrl == "" && true {
    errs = append(errs, "missing API_URL")
  }
  if c.Timeout == "" && false {
    errs = append(errs, "missing TIMEOUT")
  }
  if c.Feature == "" && true {
    errs = append(errs, "missing FEATURE")
  }
  return errs
}