# Generated by env-type-generator
from pydantic import BaseSettings, Field, ValidationError

class Env(BaseSettings):
    api_url: str = Field(...)
    timeout: str = Field('10s')
    feature: str = Field(...)

    class Config:
        case_sensitive = True

def load_env(**kwargs) -> Env:
    try:
        return Env(**kwargs)
    except ValidationError as exc:
        raise RuntimeError(str(exc)) from exc