from pathlib import Path
from typing import Iterable

from .config import VariableDefinition
from .emitter import Emitter, ensure_dir


class GoEmitter(Emitter):
    language = "go"

    def emit(self, variables: Iterable[VariableDefinition], output_dir: Path) -> None:
        ensure_dir(output_dir)
        lines = ["// Code generated by env-type-generator; DO NOT EDIT.", "package env", "", "type Config struct {"]
        for var in variables:
            field_name = var.name.title().replace("_", "")
            required = "true" if var.required else "false"
            lines.append(f"  {field_name} string `env:\"{var.name}\" required:{required}`")
        lines.append("}\n")
        helper = ["// Validate performs basic checks on required variables.", "func (c *Config) Validate() []string {", "  var errs []string"]
        for var in variables:
            field_name = var.name.title().replace("_", "")
            helper.append(f"  if c.{field_name} == \"\" && {str(var.required).lower()} {{")
            helper.append(f"    errs = append(errs, \"missing {var.name}\")")
            helper.append("  }")
        helper.append("  return errs")
        helper.append("}")
        lines.extend(helper)
        (output_dir / "env.go").write_text("\n".join(lines), encoding="utf-8")
