from pathlib import Path
from typing import Iterable

from .config import VariableDefinition
from .emitter import Emitter, ensure_dir


class TypeScriptEmitter(Emitter):
    language = "ts"

    def emit(self, variables: Iterable[VariableDefinition], output_dir: Path) -> None:
        ensure_dir(output_dir)
        lines = ["// Generated by env-type-generator", "import { z } from 'zod';", ""]
        schema_lines = ["export const envSchema = z.object({"]
        for var in variables:
            validator = self._ts_validator(var)
            schema_lines.append(f"  {var.name}: {validator},")
        schema_lines.append("});\n")
        lines.extend(schema_lines)
        lines.append("export type Env = z.infer<typeof envSchema>;\n")
        lines.append("export function loadEnv(raw: Record<string, string | undefined>): Env {\n" "  return envSchema.parse(raw);\n}")
        (output_dir / "env.ts").write_text("\n".join(lines), encoding="utf-8")

    def _ts_validator(self, var: VariableDefinition) -> str:
        base = "z.string()"
        if var.type == "number":
            base = "z.string().transform((v) => Number(v))"
        elif var.type == "boolean":
            base = "z.enum(['true','false','1','0']).transform((v) => v === 'true' || v === '1')"
        elif var.type == "enum" and var.enum:
            base = f"z.enum([{', '.join([repr(v) for v in var.enum])}])"
        elif var.type == "url":
            base = "z.string().url()"
        elif var.type == "duration":
            base = "z.string().regex(/^[0-9]+s?$/).transform((v) => Number(v.replace('s', ''))*1000)"
        elif var.type == "json":
            base = "z.string().transform((v) => JSON.parse(v))"

        if not var.required:
            base = f"{base}.optional()"
        if var.default is not None:
            base = f"{base}.default({repr(var.default)})"
        if var.deprecated:
            base = f"{base}.describe('deprecated')"
        return base
