from pathlib import Path
from typing import Iterable

from .config import VariableDefinition
from .emitter import Emitter, ensure_dir


class PythonEmitter(Emitter):
    language = "python"

    def emit(self, variables: Iterable[VariableDefinition], output_dir: Path) -> None:
        ensure_dir(output_dir)
        lines = ["# Generated by env-type-generator", "from pydantic import BaseSettings, Field, ValidationError", ""]
        lines.append("class Env(BaseSettings):")
        for var in variables:
            default = "..." if var.required else repr(var.default)
            description = f"description='{var.description}'" if var.description else ""
            field_args = ", ".join([arg for arg in [description] if arg])
            field_expr = f"Field({default}{', ' + field_args if field_args else ''})"
            lines.append(f"    {var.name.lower()}: str = {field_expr}")
        lines.append("""
    class Config:
        case_sensitive = True
""")
        helper = [
            "def load_env(**kwargs) -> Env:",
            "    try:",
            "        return Env(**kwargs)",
            "    except ValidationError as exc:",
            "        raise RuntimeError(str(exc)) from exc",
        ]
        (output_dir / "env.py").write_text("\n".join(lines + helper), encoding="utf-8")
